### ISSUE TITLE
Fragment matching out of the box via a config

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-graphql/ember-apollo-client#107]
The apollo service itself is extensible, but would it make sense to make [fragment matching](https://www.apollographql.com/docs/react/recipes/fragment-matching.html) made available out of the box and may be drive it via a config option?

**Comment by josemarluedke** [comment]
Since most of the more advanced configurations require users to overwrite the service, I think that having this be done the same way should be fine. 

What do you think?

**Comment by sivakumar-kailasam** [comment]
SGTM 🙂
