### ISSUE TITLE
Enable multiple backends communication

### ISSUE THREAD

**Issue by nizarayari** [ember-graphql/ember-apollo-client#136]
It would be great to have multiple URL defined in conf/environment.js:
```javascript
apollo: {
  apiURL: '__SIMPLE_API_ENDPOINT__',
  authURL:'__SIMPLE_AUTH_ENDPOINT__'
},
```
And be able to choose the URL while calling Apollo service:
```javascript
this.get('apollo').query({
  query, 
  variables, 
  { url: 'authURL' }
})
```

**Comment by josemarluedke** [comment]
One way you could achieve something similar is by using multiple ember services. 
Create a new service that extends from apollo service, but overwrite the url there.

I believe adding a feature specific for this would not be the best approach.

One thing to note is that https://principledgraphql.com talks about having only one graph for a company. Which is something that I believe in.

**Comment by josemarluedke** [comment]
Closing this as having another service would be a good way to achieve this.
