### ISSUE TITLE
Mutation promise doesn't return results

### ISSUE THREAD

**Issue by bastianbb** [ember-graphql/ember-apollo-client#154]
When i try to use the value resulting from the mutation, for example:

```
 this.get("apollo").mutate({ mutation, variables }, "MutationName").then((result) => {
    console.log(result);
 });
```

it says 'undefined'.
I checked the network call, the response give me what i want but i'm not able to use this result after the promise is resolved.

**Comment by viniciussbs** [comment]
Can you check if the following works? It's the `mutate` call but without the second param.

```js
this.get("apollo").mutate({ mutation, variables }).then((result) => {
    console.log(result);
 });
```

**Comment by bastianbb** [comment]
I already tried this way and I get same result.

**Comment by bgentry** [comment]
Hi @bastianbb,

I would have suggested the same thing as @viniciussbs. Have you tried stepping into [the apollo service](https://github.com/bgentry/ember-apollo-client/blob/master/addon/services/apollo.js) calls in your browser debugger? It should be straightforward from there to see what's going wrong.

There are many of us using this API successfully so I suspect it has to be something specific to your setup or the API response. In either case we probably won't be able to help more without a more complete reproduction.

**Comment by christophermlne** [comment]
Are you by any chance trying to do this from within a computed property?

I discovered a few days ago that you cannot resolve a promise returned from the Apollo service from within a computed property. Solution was to not do that ;-).

**Comment by josemarluedke** [comment]
@bastianbb Are you still having this issue? Did you solve the problem?

**Comment by josemarluedke** [comment]
We have added some tests related to this, it seems that mutation does return the result. I will close this for now. Feel free to reopen if the problem persists. 

Thanks.
