### ISSUE TITLE
Error querying schemas

### ISSUE THREAD

**Issue by raphaelns-developer** [ember-graphql/ember-apollo-client#177]
I trying to query a graphql schema information, but the `copy-with-extras` is is taking the variable off:
```
query EnumTypes {
  __type(name: "EnumType") {
    enumValues {
      name
    }
  }
}
```

I was able to get the variable using `aliases`:
```
query EnumTypes {
  enumType: __type(name: "EnumType") {
    enumValues {
      name
    }
  }
}
```
But i dont know if this is the better approach or the `copy-with-extras` should be more flexible in some way.

**Comment by josemarluedke** [comment]
I will close this as copy-with-extras was removed from our codebase. See PR https://github.com/ember-graphql/ember-apollo-client/pull/312.
