### ISSUE TITLE
Options property can't be re-assigned

### ISSUE THREAD

**Issue by mariogintili** [ember-graphql/ember-apollo-client#186]
# Context

Quoting the following lines of code:

- [options property](https://github.com/bgentry/ember-apollo-client/blob/master/addon/services/apollo.js#L65)
- [clientOptions property](https://github.com/bgentry/ember-apollo-client/blob/master/addon/services/apollo.js#L100)

Seems like you wouldn't be able to re-assign properties once the client is initially instantiated. What if someone wanted to parametise some of those constructor settings based on a CP? Like for example:

```js
  options: computed('session.isAuthenticated', function() {
    if (session.get('isAuthenticated')) {
      return {
        apiURL: config.tceuFrontend.apiURL
      };
    } else {
      return {};
    }
  }),

```

**Comment by buschtoens** [comment]
I can't guarantee it, but I am pretty sure that `ApolloClient` does not allow you to change any connection related configuration parameters once instantiated.

The `apollo` service creates a new `ApolloClient` instance, when it itself is initialized, which happens automatically, when you look it up for the first time.

You can [subclass the `apollo` service](https://github.com/bgentry/ember-apollo-client#apollo-service-api) and override the options. As long as you can guarantee that all dependencies are determined _before_ the service is looked up for the first time, this would work.

**Comment by buschtoens** [comment]
Sorry, your reply slipped past my attention.

> under that now, wouldn't it make sense for the `client` property to be a CP that re-instantiates a client, and has as dependent keys all these options one might change?

I don't think this would be a good idea, as you tear down all of Apollo, including the cache and any local state with it, if I am not mistaken. This can become a major foot gun, if you accidentally change these properties.

**Comment by josemarluedke** [comment]
I agree with @buschtoens here.

Apollo does not allow to change config after initialized. I would actually create a new service extending from ember-apollo-client for the case where your users are authenticated.

**Comment by mariogintili** [comment]
@josemarluedke @buschtoens 

> I would actually create a new service extending from ember-apollo-client for the case where your users are authenticated.

We ended up doing that for the project, basically separate services for separate APIs and whatnot. Can't say I agree with apollo's approach to state management and network interaction strategies 😄 maybe I'll write a graphQL client myself someday
