### ISSUE TITLE
TypeError: this.get(...).unsubscribeAll is not a function

### ISSUE THREAD

**Issue by czosel** [ember-graphql/ember-apollo-client#279]
When I try upgrading from `2.0.0-beta.2` to `2.0.0-beta.3`, some integration tests that use the `apollo` service fail with `TypeError: this.get(...).unsubscribeAll is not a function`.

Full test log: https://travis-ci.com/projectcaluma/ember-caluma/jobs/194232024
Example component: https://github.com/projectcaluma/ember-caluma/blob/master/addon/components/cf-field/input/table.js
And corresponding test: https://github.com/projectcaluma/ember-caluma/blob/master/tests/integration/components/cf-field/input/table-test.js

This doesn't seem to affect all the components that are using the `apollo` service, but I wasn't able to figure out what triggers the issue.

Thanks in advance!

**Comment by josemarluedke** [comment]
Are you still having this issue?

**Comment by czosel** [comment]
Sorry about the late response - yeah, the issue still persists. Here is the PR with the failing build: https://github.com/projectcaluma/ember-caluma/pull/81

**Comment by czosel** [comment]
Turns out that the issue was related to injecting the apollo service directly. See https://github.com/projectcaluma/ember-caluma/pull/439/commits/e5a0e9946d43e73ccfe17c5c1cc21b3678334077 for details.
