### ISSUE TITLE
Middleware overwrites given context

### ISSUE THREAD

**Issue by anehx** [ember-graphql/ember-apollo-client#284]
Hi,

In your documentation for an auth middleware you suggest the following:
```js
// Middleware
let authMiddleware = setContext(async request => {
  if (!token) {
    token = await localStorage.getItem('token') || null;
  }
  return {
    headers: {
      authorization: token
    }
  };
});
```
This will result in completely overriding the existing context for every request. The context would be the second argument for the function passed to `setContext`. I'm not sure if you did this on purpose or not, but we stumbled upon this trying to add a header for a single request which was overriden by our auth middleware and therefore completely ignored.

Our suggested solution for this problem is the following:
```js
// Middleware
let authMiddleware = setContext(async(request, context) => {
  if (!token) {
    token = await localStorage.getItem('token') || null;
  }

  Object.assign(context.headers, {
    headers: {
      authorization: token
    }
  });

  return context;
});
```

**Comment by josemarluedke** [comment]
Thanks for pointing this out.

I agree with your suggestion. Would you mind getting a PR updating the documentation? 

Thanks
