### ISSUE TITLE
Significance of string in query method?

### ISSUE THREAD

**Issue by topbloc-beiswenger** [ember-graphql/ember-apollo-client#285]
The query example in the docs provides the string "human" as a second argument to the query method.

`return this.get('apollo').watchQuery({ query, variables }, "human");`.

What is the significance of this string? I don't see anything in the docs, nor in Apollo's native docs. The only information I could find is in the How To GraphQL tutorial which states that the string "is specifying where in the returned data your expected data will be located." This seems extremely vague to me. I'm thinking that it refers to where in the cache the query gets allocated, but it would be great if this could be made more specific in the docs.

**Comment by christophermlne** [comment]
@topbloc-beiswenger it's for destructuring the response, using "human" as the key to use for the destructure

**Comment by topbloc-beiswenger** [comment]
@christophermlne Ah I see. Thank you!
