### ISSUE TITLE
@service decorator doesn't work with custom ApolloService

### ISSUE THREAD

**Issue by solocommand** [ember-graphql/ember-apollo-client#287]
Hi all,

Attempting to start a new project today using ember 3.10.1 and ember-apollo-client beta4. Due to the changes in beta4, the EmberObject.extends() method of customizing the Apollo service throws an error -- due to the breaking changes for native classes.

However, when attempting to set up the Apollo service with a custom link (for use with simple auth later), the `@service` decorator doesn't actually work as described in the example documentation.

```js
// services/apollo.js
import ApolloService from 'ember-apollo-client/services/apollo';
import { inject as service } from '@ember/service';
import { setContext } from 'apollo-link-context';
import { get } from '@ember/object';
import { Promise } from 'rsvp';

const authorize = (session) => {
  if (!get(session, 'isAuthenticated')) return { headers: {} };
  return new Promise((resolve) => {
    const token = get(session, 'data.authenticated.session.token');
    const headers = { Authorization: `Bearer ${token}` };
    resolve({ headers })
  });
};

export default class Service extends ApolloService {
  @service session;

  link() {
    const session = this.get('session');
    const link = super.link();
    const authLink = setContext(() => authorize(session));
    return authLink.concat(link);
  }
}
```

When the link is executed, an error is being thrown when attempting to access the decorator injected `session` service.
```
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at getCacheFor (metal.js:106)
    at Service.get [as session] (metal.js:2956)
    at getPossibleMandatoryProxyValue (metal.js:1528)
    at _get (metal.js:1607)
    at Service.get (observable.js:113)
    at Service.link (apollo.js:40)
    at Service.clientOptions (apollo.js:150)
    at Service.init (apollo.js:84)
    at initialize (core_object.js:83)
```

The `session` service is available outside the scope of this class, however.

I feel like this issue may actually be on the ember/ember-js side, but this doesn't seem to work as documented in this repo.

**Comment by solocommand** [comment]
Also it's worth noting that the `@ember-decorators/service` package was removed in 6.0, and `inject` from `@ember/service` is the decorator now. So the docs are out of date in either case, as the correct import should be
```diff
-import { inject as service } from '@ember-decorators/service';
+import { inject as service } from '@ember/service';
```

**Comment by josemarluedke** [comment]
Hello @solocommand!

Thanks for reporting. I have tried to reproduce this error with a new ember app and was not able to get the same error. You can find the code here https://github.com/josemarluedke/--repro-apollo-287. 

Things you could check in your app: 
- `ember-simple-auth` version
- `ember-cli-babel` version

Would you be able to create a reproduction of this problem?

**Comment by solocommand** [comment]
Thanks for the reply, sorry I didn't see it last night. I'll build out a reproduction shortly!

**Comment by josemarluedke** [comment]
@solocommand Are you still experimenting the original issue? Should we close this?

**Comment by solocommand** [comment]
Sorry I wasn’t able to reproduce outside my codebase, please close :)
