### ISSUE TITLE
loading state

### ISSUE THREAD

**Issue by devop911** [ember-graphql/ember-apollo-client#289]
Is there anyway to fetch the current loading state and set a variable shown in template according to it?

**Comment by christophermlne** [comment]
I usually just wrap the call to the Apollo service in an
`ember-concurrency` task. Then in the template you can do `myTask.isRunning`

**Comment by devop911** [comment]
This is a nice trick, i tried to get the loading state via apollo api, which didnt work. Would love to see this in a next Version.

**Comment by josemarluedke** [comment]
I believe using `ember-concurrency` task is a good alternative. `ember-apollo-client` always returns a promise, so you can use that as primitive to add your logic for loading. There's also Ember addons with helpers for promises that can be helpful.

https://github.com/tildeio/ember-async-await-helper
https://github.com/fivetanley/ember-promise-helpers

**Comment by josemarluedke** [comment]
Closing this in favor of alternatives.

Thanks for the discussion here.
