### ISSUE TITLE
queryManager breaks IE11

### ISSUE THREAD

**Issue by anehx** [ember-graphql/ember-apollo-client#303]
Currently, a project of mine breaks in IE11 if I'm using the `queryManager` macro (as a decorator as well as a normal CP):

`Object doesn't support property or method 'Symbol(Symbol.iterator)_9.z506oiom8fn'`

The babel config should not be a problem since other decorators from `ember-concurrency-decorators` and built in ember decorators work fine..

**Comment by josemarluedke** [comment]
This is interesting as we don't have any special code for making queryManager work as a decorator. That's all Ember. 

What version of Ember are you using? Are you also using regular computed as decorators?

**Comment by anehx** [comment]
I'm using Ember LTS v3.8.3 with `ember-decorators-polyfill`. I'm also using regular computed properties as decorators and `ember-concurrency-decorators` as well which all work fine.

**Comment by vsergiu93** [comment]
I have just stumbled on this issue, after spending 5+ hours on this I ended up forking the repository and make my app use the new repo, in this way I can debug the code easier. 

This what the error looks like in IE 11: 
![image](https://user-images.githubusercontent.com/5923843/67216634-323b5b80-f42c-11e9-8391-6f6f3788e51d.png)

It seems the problem originates from this function: https://github.com/ember-graphql/ember-apollo-client/blob/0c3d847d6c8e2b1050b901c8e7df901bb20f4771/addon/-private/apollo/query-manager.js#L27-L46

More  exactly on this line: https://github.com/ember-graphql/ember-apollo-client/blob/0c3d847d6c8e2b1050b901c8e7df901bb20f4771/addon/-private/apollo/query-manager.js#L40 where it's calling `isElementDescriptor` with `arguments` as a parameter.

I went to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) to refresh my memory on `arguments` and I found this two notes: 
- ```If you're writing ES6 compatible code, then rest parameters should be preferred.``` 

- ```“Array-like” means that arguments has a length property and properties indexed from zero, but it doesn't have Array's built-in methods like forEach() and map(). See §Description for details.```

Now after reading those two notes I wend back to IE 11 and had a closer look at the generated code and decided to use  `the rest parameter` approach  for `queryManager` and the app started working.

This is how the `queryManager` function looks after refactoring  https://github.com/vsergiu93/ember-apollo-client/blob/6d1f5a45dd3128603d2cdd6b86adc0bb593b7b74/addon/-private/apollo/query-manager.js#L27-L48. 

I'm not sure where to go from here should I submit a PR is this a viable solution?

**Comment by josemarluedke** [comment]
@vsergiu93 this is great! Could you submit a PR with your changes?

**Comment by josemarluedke** [comment]
This should now be fixed in v2.0.0-beta.7. 

Thank you @vsergiu93 and @anehx.
