### ISSUE TITLE
Why are inline queries not recommended?

### ISSUE THREAD

**Issue by jgwhite** [ember-graphql/ember-apollo-client#304]
The README states:

> Though it is not recommended, you can also use the `graphql-tag` package to write your queries within your JS file

Why isn’t this approach recommended?

**Comment by josemarluedke** [comment]
That's a good question. Maybe @bgentry could help answer that question. 

I would also be happy to remove that from the readme.

**Comment by bgentry** [comment]
My guess would be that the `.graphql`/`.gql` files can be precompiled by Webpack, whereas the inlined ones are compiled at runtime. Would be worth clarifying that point :)

Otherwise I think they're the same, because you can get syntax highlighting & autocompletion even from the `gql` tag.

**Comment by josemarluedke** [comment]
Good to know! 

There is a babel plugin to compile that at build time: https://www.apollographql.com/docs/react/recipes/babel/

@jgwhite could you be open to sending a PR clarifying this in the readme? 

Thanks.

**Comment by jgwhite** [comment]
Sure thing. I’ll submit something next week.
