### ISSUE TITLE
Move away from Evented for subscriptions

### ISSUE THREAD

**Issue by josemarluedke** [ember-graphql/ember-apollo-client#311]
`ember-apollo-client` uses the Ember mixin Evented to allow users to subscribe to changes coming from a subscription.

Ember is planning to [deprecate Evented](https://github.com/emberjs/rfcs/pull/528) and [Mixins](https://github.com/emberjs/rfcs/issues/534), which are two things we are relying on for subscriptions. Thankfully we already have deprecated the mixin for query manager.

I would like to start thinking about alternatives from the Ember Evented and move away from that as soon as possible.

@coladarci since you are the original implementer of the subscription feature here, what do you think an alternative would look like?

**Comment by coladarci** [comment]
Is there more than just that RFC to go off of? Doesn’t look like they are definitely moving forward w/ it, that said, our use of Evented is very limited; while it’d be a breaking change, we could easily come up with a new pattern, or eliminate it all together and encourage people to setup their own observer if they want updates

**Comment by buschtoens** [comment]
I recommend using the exported event utility functions over the mixin, for the following reasons:

- it's fully interoperable with the old mixin based implementations
- it's the general direction Ember is heading (reduce inherited class API surface area and use functions on objects instead), even though the RFC prescribes to remove these functions for Evented as well
- it's easier to refactor / codemod away from, once the community converges on a new standard event system

API docs: [`@ember/object/events`](http://api.emberjs.com/ember/3.12/modules/@ember%2Fobject#functions-events):
- [`addListener`](http://api.emberjs.com/ember/3.12/functions/@ember%2Fobject%2Fevents/addListener)
- [`removeListener`](http://api.emberjs.com/ember/3.12/functions/@ember%2Fobject%2Fevents/removeListener)
- [`sendEvent`](http://api.emberjs.com/ember/3.12/functions/@ember%2Fobject%2Fevents/sendEvent)

Usage example in one of my recent addons: [`ember-css-modules-active-route`](https://github.com/buschtoens/ember-css-modules-active-route/blob/aca813724d2cb76f1c0a5011081380d8800a6c24/addon/services/css-modules-active-route.ts#L51-L63)

**Comment by coladarci** [comment]
Super cool @buschtoens ; I hadn't seen that before. I'm a little confused though - from your reading are those on the chopping block as well? If not, and it's just the mixin that's going away, this is a great path forward,

**Comment by josemarluedke** [comment]
Thanks @buschtoens and @coladarci for the ideas. I have created a PR moving away from the mixin but still using ember events. Take a look at it #313 if you have time.

**Comment by josemarluedke** [comment]
Implemented in #313.
