### ISSUE TITLE
watchQuery never resolving in tests

### ISSUE THREAD

**Issue by mydea** [ember-graphql/ember-apollo-client#335]
I have a case where we call `apollo.watchQuery(...)` (via `import { queryManager } from 'ember-apollo-client';`), which never "finishes" in our test (it does resolve, but the test waiters do not continue). Replacing it with `apollo.query()` works as expected, but otherwise the test just hangs on `await visit(...)` and never resolves. Any ideas on this, or ways to work around this?

**Comment by josemarluedke** [comment]
@mydea could you create a reproduction or a test showing this problem?

**Comment by mydea** [comment]
Hmm it is in our private app, but there wasn't anything that special about it... I just used something like:

```js
let response = await this.apollo.watchQuery(...);
```

Which worked fine, but the tests simply stopped progressing and eventually timed out. Once I replace it with `this.apollo.query()` (changed nothing else) it did work as expected.

**Comment by BradLeftley** [comment]
Hello @mydea I am still experiencing this problem. What versions of Apollo client / GraphQL are you running ?

**Comment by mydea** [comment]
I am using the latest versions afaik. I have switched to use `query()` everywhere for now, as I didn't want to deal with this for now, so not sure!

**Comment by BradLeftley** [comment]
Ah okay, we don't use `watchQuery()` only `query()` so not sure what could be causing our problems.

**Comment by BradLeftley** [comment]
I think the issue was related to:
`    if (Ember.testing) {
      this._registerWaiter();
    }`
inside the `apollo.js` file. 
The requests in the tests were not triggering / no response meaning they were timing out waiting for nothing.  Which breaks the test.

**Comment by gfmartinez** [comment]
@mydea I had the same (or at least very similar) issue for a while on a new app I've been working on.

We are using MirageJS with GraphQL to create a mock server for our tests, initiating mirage via a helper that starts and shuts down the server on the beforeEach and afterEach hooks.

We found that it is necessary to use `apollo.client.clearStore()` call on the afterEach hook to be sure that watched queries (those initiated via `watchQuery` were not refetched when the mock server was shut down. Previously we had used `apollo.client.resetStore()`, but according to the [Apollo Docs for v2.6](https://www.apollographql.com/docs/react/v2.6/api/apollo-client/) the resetStore will clear cache and then refetch any watched queries...obviously not good to do if the mock server is shutdown. Switching to clearStore fixed it all up for us.

Also not sure if any of this will change when ember-apollo-client bumps Apollo version to v3.

**Comment by mydea** [comment]
Hmm, I guess it would make sense to call `clearStore()` in the `willDestroy()` hook of the apollo service? I will make a PR for that!

**Comment by christophermlne** [comment]
@gfmartinez first of all hi, secondly I would be interested in the details of how you used mirage to mock your graphql server, if you are willing to share

**Comment by josemarluedke** [comment]
Published v2.2.1 including the changes in #370, please let me know if this fixes the issue. 

Note: I would also be interested in seeing examples out there of using mirage with graphql. :D

**Comment by gfmartinez** [comment]
@christophermlne hey, man....long time! @josemarluedke hi.

I'd be happy to share some implementations. Not sure the best way...Maybe I will put a dummy app together if I have time and share.

What I do love about the Mirage/GraphQL combo is that everything works pretty well out of the box based on the schema.

The schema becomes the unifying factor between the front and back ends: makes the types for typescript, creates models for mocking, and on and on...

**Comment by christophermlne** [comment]
@gfmartinez a dummy app would be great but a gist with a config.js sample and sample test, would also be valuable. Even better if that example could be linked to from the readme for this add-on
