### ISSUE TITLE
Usage in addon

### ISSUE THREAD

**Issue by mydea** [ember-graphql/ember-apollo-client#340]
I am trying to use this in an addon, which connects to an external GraphQL API. But it seems that it is not picking up the .graphql files correctly, e.g. I have:

```addon/gql/queries/my-query.graphql```

And am trying to import it as

```js
import query from 'my-addon/gql/queries/my-query.graphql';
```

But it is not found - am I doing this wrong? Or is there another way to accomplish this?

**Comment by mydea** [comment]
After some playing around, I got it to work by adding this to the addons `index.js`:

```js
setupPreprocessorRegistry(type, registry) {
    if (type === 'self') {
      registry.add('js', {
        name: require('./package').name,
        ext: 'graphql',
        toTree(tree) {
          const GraphQLFilter = require('broccoli-graphql-filter');

          return new GraphQLFilter(tree, {
            keepExtension: true,
          });
        },
      });
    }
  },
```

If somebody else runs into this issue in the future, might be helpful!

**Comment by scytalezero** [comment]
Thank you for posting your solution! For reference, this also works in engines, even lazy loaded.
