### ISSUE TITLE
Plans to migrate to apollo-client 3.0

### ISSUE THREAD

**Issue by wuarmin** [ember-graphql/ember-apollo-client#357]
Hello!
Thanks for this addon. Are there plans to migrate to apollo-client 3.0. Are there barriers? Please let me know.

best regards

**Comment by josemarluedke** [comment]
HI @wuarmin!

Yes, we do plan to migrate to v3. There is an open PR already: #355. There are a few additional things that need to be done there, so I hope to get to that in the next week or so.

**Comment by wuarmin** [comment]
Hey @josemarluedke 
thank you for the info! Great to hear 🙂. 
Best regards

**Comment by josemarluedke** [comment]
Hi @wuarmin I just released the first beta version of ember-apollo-client containing `@apollo/client` v3.

Check it out and report any issues: v3.0.0-beta.1.
