### ISSUE TITLE
ember-fetch polyfill causing error with default settings

### ISSUE THREAD

**Issue by brandonmarino** [ember-graphql/ember-apollo-client#366]
Hey there! 

Following the base configuration guide in the readme with a vanilla ember octane project leads to the following error:

![image](https://user-images.githubusercontent.com/7682123/90067324-f1fbe100-dcbc-11ea-93a3-e81fd97c4623.png)

We narrowed the cause down to `ember-fetch`. We found this closed issue on their git being discussed with a solution: https://github.com/ember-cli/ember-fetch/issues/45#issuecomment-448689032

Tested that solution with our project and it's working.

So, from what I can gather, the issue either exists within `ember-fetch` OR with how `ember-apollo-client` configures `ember-fetch`. Or perhaps this is just a case of a missing step in the docs.

**Comment by alexhancock** [comment]
:+1:

Does anyone have thoughts on this?

**Comment by josemarluedke** [comment]
This is interesting. I think you would need to overwrite the default link options to pass a different fetch.

It would look something like this:

```js

import ApolloService from 'ember-apollo-client/services/apollo';
import { createHttpLink } from '@apollo/client/core';
import { isPresent } from '@ember/utils';

class OverriddenApolloService extends ApolloService {
  link() {
    const { apiURL, requestCredentials } = this.options;
    const linkOptions = { uri: apiURL, fetch };

    if (isPresent(requestCredentials)) {
      linkOptions.credentials = requestCredentials;
    }
    return createHttpLink(linkOptions);
  }
}
```

Let me know if this helps.

**Comment by levimoore** [comment]
If anyone ends up here because of the above error, adding this to your ember-cli-build.js file will fix it. 

`module.exports = function (defaults) {
  let app = new EmberApp(defaults, {
    'ember-fetch': {
      preferNative: true
    },`
