### ISSUE TITLE
Error while processing route: locale.index Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql

### ISSUE THREAD

**Issue by lionelrudaz** [ember-graphql/ember-apollo-client#367]
Hi everybody,

Starting with GraphQL, so perhaps my question is completely silly. I init my project yesterday with a .graphql file and was able to load my data with a fetch query.

Today, I retry the same request, and I've got the following error:

`Error while processing route: locale.index Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql`

I've tried to execute my query with a gql tag from the JavaScript fille, it's working indeed. But why is it suddenly not working with the .graphql file? 

![Capture d’écran 2020-08-20 à 18 17 25](https://user-images.githubusercontent.com/592678/90797904-84c9fa80-e311-11ea-875a-93da47e234db.png)

This is my call:

```
import Route from '@ember/routing/route';
import { queryManager } from "ember-apollo-client";
import collectionsQuery from "myproject/graphql/collections.graphql";


export default class ApplicationRoute extends Route {
  @queryManager apollo;

  async model() {
    const collections = await this.apollo.watchQuery({ collectionsQuery }, "catalogue.children");
    console.log(collections);
  }
}
```

Here's my graphql file:

```
query {
  catalogue(language: "en", path: "/collections") {
    id
    children {
      id
      name
      type
      shape {
        name
      }
    }
  }
}
```

I've tried to change the parameter to keep the extension of not, same issue. 

Let me know if you need more information.

Cheers,

Lionel

**Comment by josemarluedke** [comment]
@lennyburdette are you still having this issue? 

We process all graphql, so you shouldn't have this issue. I would check if you have the `keepGraphqlFileExtension ` set to `true` in your app.

https://github.com/ember-graphql/ember-apollo-client#build-time-configuration

**Comment by topbloc-beiswenger** [comment]
I also seem to be getting this and created a replication repo -> https://github.com/topbloc-beiswenger/ember-apollo-client-import-bug. Please let me know if there's anything I'm missing.

**Comment by awarrenlove** [comment]
I ran into this issue as well, and it turns out the error message is a complete red herring. The actual problem is the property name in the object. It must be `query`, so in your case you need to pass in `{ query: collectionsQuery }` as the first parameter.

**Comment by lionelrudaz** [comment]
OK got it. So yeah, the error message wasn't clear and since the example shows a variable that's called query, then I wasn't able to figure it out. I believe we can close this one then.
