### ISSUE TITLE
Regression: Array is returned as object from resultKey on v3.0: 

### ISSUE THREAD

**Issue by johanrd** [ember-graphql/ember-apollo-client#373]
After upgrade from v2.2.0 to v3.0.0 arrays are returned as objects:

```Javascript
async model() {
    return this.apollo.watchQuery({query: getExampleArray}, 'exampleArray')
}
```
Returns:
```Javascript
model: {}
```

When looking at the [changelog for apollo.js line 74](https://github.com/ember-graphql/ember-apollo-client/compare/v2.2.1...v3.0.0#diff-0f072b9c308e1436b0a916a91cb2e6dbL74), there seems to be an obvious regression where the check for `isArray` seems to check for `obj` which is logically always `undefined` at the check of a query, thus `isArray` always will return `false`:

```javascript
function newDataFunc(observable, resultKey, resolve, unsubscribeFn = null) {
  let obj;

  return (newData) => {
    let dataToSend = extractNewData(resultKey, newData);

    if (dataToSend === null) {
      // see comment in extractNewData
      return;
    }

    if (isNone(obj)) {
      if (isArray(obj)) {
        obj = A(obj);
      } else {
        obj = { ...dataToSend };
      }
…
```

See PR https://github.com/ember-graphql/ember-apollo-client/pull/372 for suggested fix

**Comment by josemarluedke** [comment]
Just release v3.0.1 containing the PR #372. Thank you @johanrd for reporting and sending the PR. 

Sorry for taking so long to review this.
