### ISSUE TITLE
TS errors due to no react present

### ISSUE THREAD

**Issue by knownasilya** [ember-graphql/ember-apollo-client#383]
```sh
node_modules/@apollo/client/react/context/ApolloConsumer.d.ts:1:19 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

1 import React from 'react';
```

I heard that you can use `@apollo/core` if you aren't using react?

**Comment by josemarluedke** [comment]
To avoid this, you will need to add `"skipLibCheck": true,` to your tsconfig.json.

Unfortunately, there is no package with just the core. https://www.npmjs.com/package/@apollo/core

Instead, we import from `@apollo/client/core` which does not use React. We will still get an error about React not been present, but it is not included in the final build.

For context: https://github.com/apollographql/apollo-client/issues/7318
