### ISSUE TITLE
Tracking Apollo errors globally

### ISSUE THREAD

**Issue by viniciussbs** [ember-graphql/ember-apollo-client#47]
Is anyone tracking Apollo errors successfully? I have tried this on an instance-initializer but the event handler is never called. It's like the error event is never triggered:

```javascript
RSVP.on('error', function(error, label) {
  let message = label || error.message || 'Unknown Async Error';

  errorTrackingService.error(message, error);
});
```

**Comment by viniciussbs** [comment]
This is how I'm simulating an error:

1) open the Ember app
2) stop the API server
3) navigate to a page that load something from the API

The transition is aborted since `model()` fails because of a bad request. But this error is not caught by `Ember.onerror` nor by `RSVP`'s error event.

**Comment by bgentry** [comment]
It's entirely possible that error handling is not implemented correctly. The extent of the error handling so far is rejecting promises with the error: https://github.com/bgentry/ember-apollo-client/blob/4f35ece36fc7b60e733abffe44e1c7e671b0224f/addon/services/apollo.js#L131

Let me know if you're able to figure out where this should happen or if other calls should be made.

**Comment by josemarluedke** [comment]
Apollo Client now has `apollo-link-error` package that allows you to hook into errors. 

```js
import { onError } from "apollo-link-error";

const link = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    );
  if (networkError) console.log(`[Network error]: ${networkError}`);
});
```
More info here: https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-error

Closing this in favor of that approach.
